import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)
const text = async (path) => readFile(new URL(path, root), 'utf8')

test('ordinary Hosted Search uses DSH web provider while advanced tool is explicitly named', async () => { const source = await text('lib/index.js'); assert.match(source, /registerSearchProvider\(provider\)/u); assert.match(source, /websearch_gpt_advanced/u); assert.doesNotMatch(source, /const\s+WEB_SEARCH_TOOL_NAME\s*=\s*['"]websearch_gpt['"]/u) })
test('native compaction is remote-first rather than parallel local+remote', async () => { const source = await text('lib/index.js'); assert.doesNotMatch(source, /Promise\.allSettled\(\[localPromise,\s*remotePromise\]\)/u); assert.doesNotMatch(source, /collectLocalCompaction/u); const remoteAt = source.indexOf('requestNativeCompaction({'); const fallbackAt = source.indexOf('const stream = await next()', remoteAt); assert.ok(remoteAt >= 0 && fallbackAt > remoteAt) })
test('new checkpoints are session-log native and old v3 sidecar is read-only compatibility', async () => { const index = await text('lib/index.js'); const native = await text('lib/native-checkpoint.js'); const legacy = await text('lib/legacy-v3.js'); assert.match(native, /lcx-native-compaction-v5/u); assert.match(native, /lcx-native-compaction-v4/u); assert.match(native, /rawOutput/u); assert.match(legacy, /readFileSync/u); assert.doesNotMatch(legacy, /writeFile|renameSync|mkdirSync/u); assert.doesNotMatch(index, /CheckpointV3Store/u) })
test('native checkpoint keeps a bounded conversation-fidelity prefix before opaque compaction state', async () => { const source = await text('lib/native-checkpoint.js'); assert.match(source, /RETAINED_MESSAGE_TOKEN_BUDGET = 64_000/u); assert.match(source, /ASSISTANT_RETENTION_TOKEN_RESERVE = 24_000/u); assert.match(source, /retainedConversationPlan\(input/u); assert.match(source, /\[\.\.\.retention\.items, structuredClone\(result\.compaction\)\]/u) })
test('package targets DSH 0.1.1-rc.2 directly', async () => { const pkg = JSON.parse(await text('package.json')); assert.equal(pkg.version, '0.4.0-rc.8'); assert.equal(pkg.dependencies, undefined); assert.equal(pkg.devDependencies['@deepseek-ai/dsh-llm'], '0.1.1-rc.2'); assert.equal(pkg.peerDependencies['@deepseek-ai/dsh-attachment'], '^0.1.1-rc.2'); assert.equal(pkg.peerDependencies['@deepseek-ai/dsh-compaction-basic'], undefined); assert.equal(pkg.peerDependencies['@deepseek-ai/dsh-web'], undefined) })
test('Cordis service access is guarded by explicit runtime inject and default-export metadata', async () => { const source = await text('lib/index.js'); assert.match(source, /export const inject = \['llm', 'web'\]/u); assert.match(source, /ctx\.inject\(\['llm', 'web'\], injectedCtx => installInjected\(injectedCtx, configInput\)\)/u); assert.match(source, /apply\.inject = inject/u); assert.match(source, /apply\.Config = Config/u) })
test('Native-first pressure delays DSH prune to the emergency zone', async () => { const source = await text('lib/index.js'); assert.match(source, /auto pressure .*Native V2 first/u); assert.match(source, /emergency DSH prune allowed/u); assert.match(source, /ratioPercent < auto/u); assert.match(source, /ratioPercent < emergency/u) })
test('web_search deadline is extended without changing its model schema', async () => { const source = await text('lib/index.js'); assert.match(source, /definition\.timeoutMs/u); assert.match(source, /webSearchTimeoutSeconds/u); const client = await text('lib/client.js'); assert.match(client, /240/u) })
test('ordinary Hosted Search follows the active Agent without changing web_search schema', async () => { const source = await text('lib/index.js'); assert.match(source, /AsyncLocalStorage/u); assert.match(source, /hostedSearchRouteContext\.run\(active/u); assert.match(source, /web_search route:/u); assert.match(source, /dsh-lcx-search:/u); const hosted = await text('lib/web-search-hosted.js'); assert.match(hosted, /prompt_cache_key/u) })
test('rc.8 uses the DSH 0.1.1 request-image API directly', async () => { const source = await text('lib/dsh-responses.js'); assert.match(source, /readImageRequest/u); assert.match(source, /offloadRequestImagesWithPolicy/u); assert.doesNotMatch(source, /attachments\?\.readImage\)/u); assert.match(source, /DEFAULT_REQUEST_IMAGE_PIXEL_BUDGET = 2048 \* 2048/u); assert.match(source, /DEFAULT_REQUEST_IMAGE_MAX_BYTES = 1024 \* 1024/u) })
