import z from "@deepseek-ai/schemastery";
import type { Context, Volatile } from "@deepseek-ai/cordis";
import "@deepseek-ai/dsh-agent";
import "@deepseek-ai/dsh-tools";
import "@deepseek-ai/dsh-web";
export declare const name = "lcx-codex";
export declare const inject: string[];
type ConfigInput = {
    supportsLongCacheRetention?: unknown;
    supportsExplicitPromptCacheMode?: unknown;
    alphaCapabilityPath?: unknown;
    alphaRefPath?: unknown;
    alphaProfile?: unknown;
    alphaGroup?: unknown;
    alphaMaxOutputTokens?: unknown;
    webSearchProvider?: unknown;
    webMaxResults?: unknown;
    timeoutMs?: unknown;
    maxResponseBytes?: unknown;
    maxAttempts?: unknown;
    maxRequestImageBytes?: unknown;
    requestImagePixelBudget?: unknown;
    requestImageMaxBytes?: unknown;
    portableReplayMaxChars?: unknown;
    nativeRetentionTokenBudget?: unknown;
    assistantRetentionTokenReserve?: unknown;
    assistantRetentionPerMessageTokenCap?: unknown;
};
type LiveSettingsConfig = {
    enabled: Volatile<boolean>;
    webSearch: Volatile<boolean>;
    advancedHostedSearch: Volatile<boolean>;
    alphaSearch: Volatile<boolean>;
    grokNativeWebSearch: Volatile<boolean>;
    grokNativeXSearch: Volatile<boolean>;
    searchMediaPreview: Volatile<boolean>;
};
type HostContext = Context;
export declare const Config: z<Schemastery.ObjectS<NoInfer<{
    enabled: z<boolean, boolean, "volatile-defined">;
    webSearch: z<boolean, boolean, "volatile-defined">;
    advancedHostedSearch: z<boolean, boolean, "volatile-defined">;
    alphaSearch: z<boolean, boolean, "volatile-defined">;
    grokNativeWebSearch: z<boolean, boolean, "volatile-defined">;
    grokNativeXSearch: z<boolean, boolean, "volatile-defined">;
    searchMediaPreview: z<boolean, boolean, "volatile-defined">;
    supportsLongCacheRetention: z<boolean, boolean, "defined">;
    supportsExplicitPromptCacheMode: z<boolean, boolean, "defined">;
    alphaCapabilityPath: z<string, string, "defined">;
    alphaRefPath: z<string, string, "defined">;
    alphaProfile: z<string, string, "defined">;
    alphaGroup: z<string, string, "defined">;
    alphaMaxOutputTokens: z<number, number, "defined">;
    webSearchProvider: z<string, string, "defined">;
    webMaxResults: z<number, number, "defined">;
    timeoutMs: z<number, number, "defined">;
    maxResponseBytes: z<number, number, "defined">;
    maxAttempts: z<number, number, "defined">;
    maxRequestImageBytes: z<number, number, "defined">;
    requestImagePixelBudget: z<number, number, "defined">;
    requestImageMaxBytes: z<number, number, "defined">;
    portableReplayMaxChars: z<number, number, "defined">;
    nativeRetentionTokenBudget: z<number, number, "defined">;
    assistantRetentionTokenReserve: z<number, number, "defined">;
    assistantRetentionPerMessageTokenCap: z<number, number, "defined">;
}>>, Schemastery.ObjectT<NoInfer<{
    enabled: z<boolean, boolean, "volatile-defined">;
    webSearch: z<boolean, boolean, "volatile-defined">;
    advancedHostedSearch: z<boolean, boolean, "volatile-defined">;
    alphaSearch: z<boolean, boolean, "volatile-defined">;
    grokNativeWebSearch: z<boolean, boolean, "volatile-defined">;
    grokNativeXSearch: z<boolean, boolean, "volatile-defined">;
    searchMediaPreview: z<boolean, boolean, "volatile-defined">;
    supportsLongCacheRetention: z<boolean, boolean, "defined">;
    supportsExplicitPromptCacheMode: z<boolean, boolean, "defined">;
    alphaCapabilityPath: z<string, string, "defined">;
    alphaRefPath: z<string, string, "defined">;
    alphaProfile: z<string, string, "defined">;
    alphaGroup: z<string, string, "defined">;
    alphaMaxOutputTokens: z<number, number, "defined">;
    webSearchProvider: z<string, string, "defined">;
    webMaxResults: z<number, number, "defined">;
    timeoutMs: z<number, number, "defined">;
    maxResponseBytes: z<number, number, "defined">;
    maxAttempts: z<number, number, "defined">;
    maxRequestImageBytes: z<number, number, "defined">;
    requestImagePixelBudget: z<number, number, "defined">;
    requestImageMaxBytes: z<number, number, "defined">;
    portableReplayMaxChars: z<number, number, "defined">;
    nativeRetentionTokenBudget: z<number, number, "defined">;
    assistantRetentionTokenReserve: z<number, number, "defined">;
    assistantRetentionPerMessageTokenCap: z<number, number, "defined">;
}>>, "plain">;
export declare function compactionPressureBand(totalTokens: number, contextWindow: number, policy: {
    auto: number;
    emergency: number;
    outputReserve: number;
    headroomTokens: number;
}): {
    pressureBudget: number;
    nativeThreshold: number;
    emergencyThreshold: number;
    ratioPercent: number;
    band: string;
};
export declare function apply(ctx: HostContext, configInput: ConfigInput & LiveSettingsConfig): void;
export declare namespace apply {
    export { inject };
    export { Config };
}
export default apply;
